### PR TITLE
DEV-8 As an HT developer, I need a RightsDB gem to reduce duplication

### PR DESCRIPTION
**Pull request by moseshll**
- New repo with WIP

### CODE REVIEW

**Comment by aelkiss** [comment]
Looks like a good start, with the expectation that we need to flesh out the tests in `rights_spec.rb`. Is there any reason why the repo is private right now, or was that just the default? I don't have any concerns with making it public.

**Comment by moseshll** [comment]
I set it to private since it was an empty repo and did not anticipate the initial checkin to pass muster. I'll set it to public after the first PR is merged.

**Comment by moseshll** [comment]
Need to do a sanity check on how hathifiles and hathi_search_client codebases will deal with these models.

**Comment by aelkiss** [comment]
I looked at it a bit in terms of what might change if we were getting this data from a web service instead of a database directly. My main thought is that it might be useful to explicitly mark `load_from_db` methods as private. I think exposing the underlying database connection is _probably_ OK, but we should generally prefer to add any additional queries here rather than adding additional functionality elsewhere, again to make that migration to using a rights API easier.

**Comment by billdueber** [comment]
Looks good, certainly good enough for a first pass. We should probably use an actual container since we're likely to need one anyway, but let's go ahead and merge this and work it from there.

**Pull request merged**
